"""Every Arabic codepoint used anywhere in this project, as named constants.

Generated from the union of the pinned editions' censuses; regenerate via
tools/gen_codepoints.py when a new edition is pinned. The values are written
as backslash-u escapes on purpose: no hand-typed Arabic anywhere in the repo.
"""

SPACE = "\u0020"  # U+0020 SPACE
NO_BREAK_SPACE = "\u00a0"  # U+00A0 NO-BREAK SPACE
SMALL_DAMMA = "\u0619"  # U+0619 ARABIC SMALL DAMMA
HAMZA = "\u0621"  # U+0621 ARABIC LETTER HAMZA
ALEF_WITH_HAMZA_ABOVE = "\u0623"  # U+0623 ARABIC LETTER ALEF WITH HAMZA ABOVE
WAW_WITH_HAMZA_ABOVE = "\u0624"  # U+0624 ARABIC LETTER WAW WITH HAMZA ABOVE
ALEF_WITH_HAMZA_BELOW = "\u0625"  # U+0625 ARABIC LETTER ALEF WITH HAMZA BELOW
YEH_WITH_HAMZA_ABOVE = "\u0626"  # U+0626 ARABIC LETTER YEH WITH HAMZA ABOVE
ALEF = "\u0627"  # U+0627 ARABIC LETTER ALEF
BEH = "\u0628"  # U+0628 ARABIC LETTER BEH
TEH_MARBUTA = "\u0629"  # U+0629 ARABIC LETTER TEH MARBUTA
TEH = "\u062a"  # U+062A ARABIC LETTER TEH
THEH = "\u062b"  # U+062B ARABIC LETTER THEH
JEEM = "\u062c"  # U+062C ARABIC LETTER JEEM
HAH = "\u062d"  # U+062D ARABIC LETTER HAH
KHAH = "\u062e"  # U+062E ARABIC LETTER KHAH
DAL = "\u062f"  # U+062F ARABIC LETTER DAL
THAL = "\u0630"  # U+0630 ARABIC LETTER THAL
REH = "\u0631"  # U+0631 ARABIC LETTER REH
ZAIN = "\u0632"  # U+0632 ARABIC LETTER ZAIN
SEEN = "\u0633"  # U+0633 ARABIC LETTER SEEN
SHEEN = "\u0634"  # U+0634 ARABIC LETTER SHEEN
SAD = "\u0635"  # U+0635 ARABIC LETTER SAD
DAD = "\u0636"  # U+0636 ARABIC LETTER DAD
TAH = "\u0637"  # U+0637 ARABIC LETTER TAH
ZAH = "\u0638"  # U+0638 ARABIC LETTER ZAH
AIN = "\u0639"  # U+0639 ARABIC LETTER AIN
GHAIN = "\u063a"  # U+063A ARABIC LETTER GHAIN
TATWEEL = "\u0640"  # U+0640 ARABIC TATWEEL
FEH = "\u0641"  # U+0641 ARABIC LETTER FEH
QAF = "\u0642"  # U+0642 ARABIC LETTER QAF
KAF = "\u0643"  # U+0643 ARABIC LETTER KAF
LAM = "\u0644"  # U+0644 ARABIC LETTER LAM
MEEM = "\u0645"  # U+0645 ARABIC LETTER MEEM
NOON = "\u0646"  # U+0646 ARABIC LETTER NOON
HEH = "\u0647"  # U+0647 ARABIC LETTER HEH
WAW = "\u0648"  # U+0648 ARABIC LETTER WAW
ALEF_MAKSURA = "\u0649"  # U+0649 ARABIC LETTER ALEF MAKSURA
YEH = "\u064a"  # U+064A ARABIC LETTER YEH
FATHATAN = "\u064b"  # U+064B ARABIC FATHATAN
DAMMATAN = "\u064c"  # U+064C ARABIC DAMMATAN
KASRATAN = "\u064d"  # U+064D ARABIC KASRATAN
FATHA = "\u064e"  # U+064E ARABIC FATHA
DAMMA = "\u064f"  # U+064F ARABIC DAMMA
KASRA = "\u0650"  # U+0650 ARABIC KASRA
SHADDA = "\u0651"  # U+0651 ARABIC SHADDA
SUKUN = "\u0652"  # U+0652 ARABIC SUKUN
MADDAH_ABOVE = "\u0653"  # U+0653 ARABIC MADDAH ABOVE
HAMZA_ABOVE = "\u0654"  # U+0654 ARABIC HAMZA ABOVE
HAMZA_BELOW = "\u0655"  # U+0655 ARABIC HAMZA BELOW
SUBSCRIPT_ALEF = "\u0656"  # U+0656 ARABIC SUBSCRIPT ALEF
INVERTED_DAMMA = "\u0657"  # U+0657 ARABIC INVERTED DAMMA
FATHA_WITH_TWO_DOTS = "\u065e"  # U+065E ARABIC FATHA WITH TWO DOTS
SUPERSCRIPT_ALEF = "\u0670"  # U+0670 ARABIC LETTER SUPERSCRIPT ALEF
ALEF_WASLA = "\u0671"  # U+0671 ARABIC LETTER ALEF WASLA
ALEF_WITH_WAVY_HAMZA_ABOVE = "\u0672"  # U+0672 ARABIC LETTER ALEF WITH WAVY HAMZA ABOVE
TCHEHEH = "\u0687"  # U+0687 ARABIC LETTER TCHEHEH
NOON_GHUNNA = "\u06ba"  # U+06BA ARABIC LETTER NOON GHUNNA
SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA = "\u06d6"  # U+06D6 ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA
SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA = "\u06d7"  # U+06D7 ARABIC SMALL HIGH LIGATURE QAF WITH LAM WITH ALEF MAKSURA
SMALL_HIGH_MEEM_INITIAL_FORM = "\u06d8"  # U+06D8 ARABIC SMALL HIGH MEEM INITIAL FORM
SMALL_HIGH_JEEM = "\u06da"  # U+06DA ARABIC SMALL HIGH JEEM
SMALL_HIGH_THREE_DOTS = "\u06db"  # U+06DB ARABIC SMALL HIGH THREE DOTS
SMALL_HIGH_SEEN = "\u06dc"  # U+06DC ARABIC SMALL HIGH SEEN
START_OF_RUB_EL_HIZB = "\u06de"  # U+06DE ARABIC START OF RUB EL HIZB
SMALL_HIGH_ROUNDED_ZERO = "\u06df"  # U+06DF ARABIC SMALL HIGH ROUNDED ZERO
SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO = "\u06e0"  # U+06E0 ARABIC SMALL HIGH UPRIGHT RECTANGULAR ZERO
SMALL_HIGH_DOTLESS_HEAD_OF_KHAH = "\u06e1"  # U+06E1 ARABIC SMALL HIGH DOTLESS HEAD OF KHAH
SMALL_HIGH_MEEM_ISOLATED_FORM = "\u06e2"  # U+06E2 ARABIC SMALL HIGH MEEM ISOLATED FORM
SMALL_LOW_SEEN = "\u06e3"  # U+06E3 ARABIC SMALL LOW SEEN
SMALL_HIGH_MADDA = "\u06e4"  # U+06E4 ARABIC SMALL HIGH MADDA
SMALL_WAW = "\u06e5"  # U+06E5 ARABIC SMALL WAW
SMALL_YEH = "\u06e6"  # U+06E6 ARABIC SMALL YEH
SMALL_HIGH_YEH = "\u06e7"  # U+06E7 ARABIC SMALL HIGH YEH
SMALL_HIGH_NOON = "\u06e8"  # U+06E8 ARABIC SMALL HIGH NOON
PLACE_OF_SAJDAH = "\u06e9"  # U+06E9 ARABIC PLACE OF SAJDAH
EMPTY_CENTRE_LOW_STOP = "\u06ea"  # U+06EA ARABIC EMPTY CENTRE LOW STOP
EMPTY_CENTRE_HIGH_STOP = "\u06eb"  # U+06EB ARABIC EMPTY CENTRE HIGH STOP
ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE = "\u06ec"  # U+06EC ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE
SMALL_LOW_MEEM = "\u06ed"  # U+06ED ARABIC SMALL LOW MEEM
SIGN_SINDHI_POSTPOSITION_MEN = "\u06fe"  # U+06FE ARABIC SIGN SINDHI POSTPOSITION MEN

ALL = {
    "AIN": AIN,
    "ALEF": ALEF,
    "ALEF_MAKSURA": ALEF_MAKSURA,
    "ALEF_WASLA": ALEF_WASLA,
    "ALEF_WITH_HAMZA_ABOVE": ALEF_WITH_HAMZA_ABOVE,
    "ALEF_WITH_HAMZA_BELOW": ALEF_WITH_HAMZA_BELOW,
    "ALEF_WITH_WAVY_HAMZA_ABOVE": ALEF_WITH_WAVY_HAMZA_ABOVE,
    "BEH": BEH,
    "DAD": DAD,
    "DAL": DAL,
    "DAMMA": DAMMA,
    "DAMMATAN": DAMMATAN,
    "EMPTY_CENTRE_HIGH_STOP": EMPTY_CENTRE_HIGH_STOP,
    "EMPTY_CENTRE_LOW_STOP": EMPTY_CENTRE_LOW_STOP,
    "FATHA": FATHA,
    "FATHATAN": FATHATAN,
    "FATHA_WITH_TWO_DOTS": FATHA_WITH_TWO_DOTS,
    "FEH": FEH,
    "GHAIN": GHAIN,
    "HAH": HAH,
    "HAMZA": HAMZA,
    "HAMZA_ABOVE": HAMZA_ABOVE,
    "HAMZA_BELOW": HAMZA_BELOW,
    "HEH": HEH,
    "INVERTED_DAMMA": INVERTED_DAMMA,
    "JEEM": JEEM,
    "KAF": KAF,
    "KASRA": KASRA,
    "KASRATAN": KASRATAN,
    "KHAH": KHAH,
    "LAM": LAM,
    "MADDAH_ABOVE": MADDAH_ABOVE,
    "MEEM": MEEM,
    "NOON": NOON,
    "NOON_GHUNNA": NOON_GHUNNA,
    "NO_BREAK_SPACE": NO_BREAK_SPACE,
    "PLACE_OF_SAJDAH": PLACE_OF_SAJDAH,
    "QAF": QAF,
    "REH": REH,
    "ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE": ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE,
    "SAD": SAD,
    "SEEN": SEEN,
    "SHADDA": SHADDA,
    "SHEEN": SHEEN,
    "SIGN_SINDHI_POSTPOSITION_MEN": SIGN_SINDHI_POSTPOSITION_MEN,
    "SMALL_DAMMA": SMALL_DAMMA,
    "SMALL_HIGH_DOTLESS_HEAD_OF_KHAH": SMALL_HIGH_DOTLESS_HEAD_OF_KHAH,
    "SMALL_HIGH_JEEM": SMALL_HIGH_JEEM,
    "SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA": SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA,
    "SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA": SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA,
    "SMALL_HIGH_MADDA": SMALL_HIGH_MADDA,
    "SMALL_HIGH_MEEM_INITIAL_FORM": SMALL_HIGH_MEEM_INITIAL_FORM,
    "SMALL_HIGH_MEEM_ISOLATED_FORM": SMALL_HIGH_MEEM_ISOLATED_FORM,
    "SMALL_HIGH_NOON": SMALL_HIGH_NOON,
    "SMALL_HIGH_ROUNDED_ZERO": SMALL_HIGH_ROUNDED_ZERO,
    "SMALL_HIGH_SEEN": SMALL_HIGH_SEEN,
    "SMALL_HIGH_THREE_DOTS": SMALL_HIGH_THREE_DOTS,
    "SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO": SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO,
    "SMALL_HIGH_YEH": SMALL_HIGH_YEH,
    "SMALL_LOW_MEEM": SMALL_LOW_MEEM,
    "SMALL_LOW_SEEN": SMALL_LOW_SEEN,
    "SMALL_WAW": SMALL_WAW,
    "SMALL_YEH": SMALL_YEH,
    "SPACE": SPACE,
    "START_OF_RUB_EL_HIZB": START_OF_RUB_EL_HIZB,
    "SUBSCRIPT_ALEF": SUBSCRIPT_ALEF,
    "SUKUN": SUKUN,
    "SUPERSCRIPT_ALEF": SUPERSCRIPT_ALEF,
    "TAH": TAH,
    "TATWEEL": TATWEEL,
    "TCHEHEH": TCHEHEH,
    "TEH": TEH,
    "TEH_MARBUTA": TEH_MARBUTA,
    "THAL": THAL,
    "THEH": THEH,
    "WAW": WAW,
    "WAW_WITH_HAMZA_ABOVE": WAW_WITH_HAMZA_ABOVE,
    "YEH": YEH,
    "YEH_WITH_HAMZA_ABOVE": YEH_WITH_HAMZA_ABOVE,
    "ZAH": ZAH,
    "ZAIN": ZAIN,
}

NAME_BY_CP = {f"{ord(v):04X}": k for k, v in ALL.items()}
